package book.dhb.numericalmethods.utilityclasses;


/**
 * This class was generated by a SmartGuide.
 * 
 */
public class IntegerField extends ValuedField
{
	private static final long serialVersionUID = 1L;
	
	/**
	 * minimum
	 */
	private int minimum;
	/**
	 * maximum
	 */
	private int maximum;



	/**
	 * Simple Constructor method.
	 * @param size number of columns of the text field.
	 */
	public IntegerField( int size)
	{
		super("", size);
	}
	/**
	 * Full Constructor method.
	 * @param defaultValue int value displayed in the text field.
	 * @param size int number of columns of the text field. 
	 * @param low int minimum allowed value. 
	 * @param high int maximum allowed value. 
	 */
	public IntegerField( int defaultValue, int size, int low, int high)
	{
		super( "" + defaultValue, size);
		setMinimum( low);
		setMaximum( high);
	}
	/**
	 * Decodes and retrieves the value which has been entered in the text field. 
	 * @return the decoded value. 
	 */
	public int getValue() throws NumberFormatException
	{
		int value;

		value = Integer.valueOf( getText().trim()).intValue();
		if ( minimumDefined && value < minimum )
			throw new NumberFormatException();
		if ( maximumDefined && value > maximum )
			throw new NumberFormatException();
		return value;
	}
	/**
	 * Defines the maximum value which may be entered in the text field. 
	 * @param low int maximum allowed value. 
	 */
	public void setMaximum( int low)
	{
		maximum = low;
		maximumDefined = true;
	}
	/**
	 * Defines the minimum value which may be entered in the text field. 
	 * @param low int minimum allowed value. 
	 */
	public void setMinimum( int low)
	{
		minimum = low;
		minimumDefined = true;
	}
}